// Language utilities - endonyms for ISO language codes
namespace Receiver {

    public class Languages {
        public static string translate(string code) {
            switch (code.up()) {
                case "AF": return "Afrikaans";
                case "AK": return "Akan";
                case "AM": return "አማርኛ";
                case "AR": return "العربية";
                case "AS": return "অসমীয়া";
                case "AST": return "Asturianu";
                case "AY": return "Aymar aru";
                case "AZ": return "Azərbaycan";
                case "BAR": return "Boarisch";
                case "BE": return "Беларуская";
                case "BG": return "Български";
                case "BI": return "Bislama";
                case "BM": return "Bamanankan";
                case "BN": return "বাংলা";
                case "BO": return "བོད་སྐད";
                case "BR": return "Brezhoneg";
                case "BS": return "Bosanski";
                case "CA": return "Català";
                case "CMN": return "普通话";
                case "CR": return "ᓀᐦᐃᔭᐍᐏᐣ";
                case "CS": return "Čeština";
                case "CY": return "Cymraeg";
                case "DA": return "Dansk";
                case "DE": return "Deutsch";
                case "EL": return "Ελληνικά";
                case "EN": return "English";
                case "EO": return "Esperanto";
                case "ES": return "Español";
                case "ES-419": return "Español (Latinoamérica)";
                case "ET": return "Eesti";
                case "EU": return "Euskara";
                case "FA": return "فارسی";
                case "FI": return "Suomi";
                case "FIL": return "Filipino";
                case "FJ": return "Vosa Vakaviti";
                case "FO": return "Føroyskt";
                case "FR": return "Français";
                case "GA": return "Gaeilge";
                case "GD": return "Gàidhlig";
                case "GL": return "Galego";
                case "GN": return "Avañeʼẽ";
                case "GSW": return "Schwiizerdütsch";
                case "GU": return "ગુજરાતી";
                case "GV": return "Gaelg";
                case "HA": return "Hausa";
                case "HAK": return "客家語";
                case "HE": return "עברית";
                case "HI": return "हिन्दी";
                case "HR": return "Hrvatski";
                case "HU": return "Magyar";
                case "HY": return "Հայերեն";
                case "ID": return "Bahasa Indonesia";
                case "IS": return "Íslenska";
                case "IT": return "Italiano";
                case "JA": return "日本語";
                case "JV": return "Basa Jawa";
                case "KA": return "ქართული";
                case "KK": return "Қазақша";
                case "KM": return "ខ្មែរ";
                case "KN": return "ಕನ್ನಡ";
                case "KO": return "한국어";
                case "KS": return "कॉशुर";
                case "KU": return "Kurdî";
                case "KV": return "Коми";
                case "KW": return "Kernewek";
                case "LA": return "Latina";
                case "LB": return "Lëtzebuergesch";
                case "LN": return "Lingála";
                case "LT": return "Lietuvių";
                case "LV": return "Latviešu";
                case "MG": return "Malagasy";
                case "MI": return "Te Reo Māori";
                case "MK": return "Македонски";
                case "ML": return "മലയാളം";
                case "MN": return "Монгол";
                case "MR": return "मराठी";
                case "MS": return "Bahasa Melayu";
                case "MT": return "Malti";
                case "MY": return "မြန်မာ";
                case "NDS": return "Plattdüütsch";
                case "NE": return "नेपाली";
                case "NL": return "Nederlands";
                case "NO": return "Norsk";
                case "NV": return "Diné bizaad";
                case "OC": return "Occitan";
                case "OM": return "Afaan Oromoo";
                case "PA": return "ਪੰਜਾਬੀ";
                case "PI": return "पालि";
                case "PL": return "Polski";
                case "PT": return "Português";
                case "QU": return "Runasimi";
                case "RM": return "Rumantsch";
                case "RO": return "Română";
                case "RU": return "Русский";
                case "SA": return "संस्कृतम्";
                case "SC": return "Sardu";
                case "SD": return "سنڌي";
                case "SI": return "සිංහල";
                case "SK": return "Slovenčina";
                case "SL": return "Slovenščina";
                case "SM": return "Gagana Samoa";
                case "SN": return "ChiShona";
                case "SO": return "Soomaali";
                case "SQ": return "Shqip";
                case "SR": return "Српски";
                case "SV": return "Svenska";
                case "SW": return "Kiswahili";
                case "SWG": return "Schwäbisch";
                case "TA": return "தமிழ்";
                case "TE": return "తెలుగు";
                case "TH": return "ไทย";
                case "TK": return "Türkmen";
                case "TO": return "Lea fakatonga";
                case "TR": return "Türkçe";
                case "TT": return "Татарча";
                case "TW": return "Twi";
                case "TY": return "Reo Tahiti";
                case "UK": return "Українська";
                case "UR": return "اردو";
                case "UZ": return "Oʻzbek";
                case "VI": return "Tiếng Việt";
                case "WEN": return "Serbšćina";
                case "XH": return "IsiXhosa";
                case "YI": return "ייִדיש";
                case "YO": return "Yorùbá";
                case "YUE": return "粵語";
                case "ZH": return "中文";
                case "ZU": return "IsiZulu";
                default: return code;
            }
        }
    }
}
