// Language utilities - endonyms for ISO language codes
namespace Receiver {

    public class Languages {
        public static string translate(string code) {
            switch (code) {
                case "af": return "Afrikaans";
                case "ak": return "Akan";
                case "am": return "አማርኛ";
                case "ar": return "العربية";
                case "as": return "অসমীয়া";
                case "ast": return "Asturianu";
                case "ay": return "Aymar aru";
                case "az": return "Azərbaycan";
                case "bar": return "Boarisch";
                case "be": return "Беларуская";
                case "bg": return "Български";
                case "bi": return "Bislama";
                case "bm": return "Bamanankan";
                case "bn": return "বাংলা";
                case "bo": return "བོད་སྐད";
                case "br": return "Brezhoneg";
                case "bs": return "Bosanski";
                case "ca": return "Català";
                case "cmn": return "普通话";
                case "cr": return "ᓀᐦᐃᔭᐍᐏᐣ";
                case "cs": return "Čeština";
                case "cy": return "Cymraeg";
                case "da": return "Dansk";
                case "de": return "Deutsch";
                case "el": return "Ελληνικά";
                case "en": return "English";
                case "eo": return "Esperanto";
                case "es": return "Español";
                case "es-419": return "Español (Latinoamérica)";
                case "et": return "Eesti";
                case "eu": return "Euskara";
                case "fa": return "فارسی";
                case "fi": return "Suomi";
                case "fil": return "Filipino";
                case "fj": return "Vosa Vakaviti";
                case "fo": return "Føroyskt";
                case "fr": return "Français";
                case "ga": return "Gaeilge";
                case "gd": return "Gàidhlig";
                case "gl": return "Galego";
                case "gn": return "Avañeʼẽ";
                case "gsw": return "Schwiizerdütsch";
                case "gu": return "ગુજરાતી";
                case "gv": return "Gaelg";
                case "ha": return "Hausa";
                case "hak": return "客家語";
                case "he": return "עברית";
                case "hi": return "हिन्दी";
                case "hr": return "Hrvatski";
                case "hu": return "Magyar";
                case "hy": return "Հայերેն";
                case "id": return "Bahasa Indonesia";
                case "is": return "Íslenska";
                case "it": return "Italiano";
                case "ja": return "日本語";
                case "jv": return "Basa Jawa";
                case "ka": return "ქართული";
                case "kk": return "Қазақша";
                case "km": return "ខ្មែរ";
                case "kn": return "ಕನ್ನಡ";
                case "ko": return "한국어";
                case "ks": return "कॉशुर";
                case "ku": return "Kurdî";
                case "kv": return "Коми";
                case "kw": return "Kernewek";
                case "la": return "Latina";
                case "lb": return "Lëtzebuergesch";
                case "ln": return "Lingála";
                case "lt": return "Lietuvių";
                case "lv": return "Latviešu";
                case "mg": return "Malagasy";
                case "mi": return "Te Reo Māori";
                case "mk": return "Македонски";
                case "ml": return "മലയാളം";
                case "mn": return "Монгол";
                case "mr": return "मराठी";
                case "ms": return "Bahasa Melayu";
                case "mt": return "Malti";
                case "my": return "မြန်မာ";
                case "nds": return "Plattdüütsch";
                case "ne": return "नेपाली";
                case "nl": return "Nederlands";
                case "no": return "Norsk";
                case "nv": return "Diné bizaad";
                case "oc": return "Occitan";
                case "om": return "Afaan Oromoo";
                case "pa": return "ਪੰਜਾਬੀ";
                case "pi": return "पालि";
                case "pl": return "Polski";
                case "pt": return "Português";
                case "qu": return "Runasimi";
                case "rm": return "Rumantsch";
                case "ro": return "Română";
                case "ru": return "Русский";
                case "sa": return "संस्कृतम्";
                case "sc": return "Sardu";
                case "sd": return "سنڌي";
                case "si": return "සිංහල";
                case "sk": return "Slovenčina";
                case "sl": return "Slovenščina";
                case "sm": return "Gagana Samoa";
                case "sn": return "ChiShona";
                case "so": return "Soomaali";
                case "sq": return "Shqip";
                case "sr": return "Српски";
                case "sv": return "Svenska";
                case "sw": return "Kiswahili";
                case "swg": return "Schwäbisch";
                case "ta": return "தமிழ்";
                case "te": return "తెలుగు";
                case "th": return "ไทย";
                case "tk": return "Türkmen";
                case "to": return "Lea fakatonga";
                case "tr": return "Türkçe";
                case "tt": return "Татарча";
                case "tw": return "Twi";
                case "ty": return "Reo Tahiti";
                case "uk": return "Українська";
                case "ur": return "اردو";
                case "uz": return "Oʻzbek";
                case "vi": return "Tiếng Việt";
                case "wen": return "Serbšćina";
                case "xh": return "IsiXhosa";
                case "yi": return "ייִדיש";
                case "yo": return "Yorùbá";
                case "yue": return "粵語";
                case "zh": return "中文";
                case "zu": return "IsiZulu";
                default: return code;
            }
        }
    }
}
