// Language utilities - translations for ISO language codes
namespace Receiver {

    public class Languages {
        public static string translate(string code) {
            switch (code.up()) {
                case "AF": return _("Afrikaans");
                case "AK": return _("Akan");
                case "AM": return _("Amharic");
                case "AR": return _("Arabic");
                case "AS": return _("Assamese");
                case "AST": return _("Spanish (Asturian)");
                case "AY": return _("Aymara");
                case "AZ": return _("Azerbaijani");
                case "BAR": return _("Bavarian");
                case "BE": return _("Belarusian");
                case "BG": return _("Bulgarian");
                case "BI": return _("Bislama");
                case "BM": return _("Bambara");
                case "BN": return _("Bengali");
                case "BO": return _("Tibetan");
                case "BR": return _("Breton");
                case "BS": return _("Bosnian");
                case "CA": return _("Catalan");
                case "CMN": return _("Chinese (Mandarin)");
                case "CR": return _("Cree");
                case "CS": return _("Czech");
                case "CY": return _("Welsh");
                case "DA": return _("Danish");
                case "DE": return _("German");
                case "EL": return _("Greek");
                case "EN": return _("English");
                case "EO": return _("Esperanto");
                case "ES": return _("Spanish");
                case "ES-419": return _("Spanish (Latin American)");
                case "ET": return _("Estonian");
                case "EU": return _("Basque");
                case "FA": return _("Persian");
                case "FI": return _("Finnish");
                case "FIL": return _("Filipino");
                case "FJ": return _("Fijian");
                case "FO": return _("Faroese");
                case "FR": return _("French");
                case "GA": return _("Irish");
                case "GD": return _("Scottish Gaelic");
                case "GL": return _("Galician");
                case "GN": return _("Guarani");
                case "GSW": return _("German (Swiss)");
                case "GU": return _("Gujarati");
                case "GV": return _("Manx");
                case "HA": return _("Hausa");
                case "HAK": return _("Chinese (Hakka)");
                case "HE": return _("Hebrew");
                case "HI": return _("Hindi");
                case "HR": return _("Croatian");
                case "HU": return _("Hungarian");
                case "HY": return _("Armenian");
                case "ID": return _("Indonesian");
                case "IS": return _("Icelandic");
                case "IT": return _("Italian");
                case "JA": return _("Japanese");
                case "JV": return _("Javanese");
                case "KA": return _("Georgian");
                case "KK": return _("Kazakh");
                case "KM": return _("Khmer");
                case "KN": return _("Kannada");
                case "KO": return _("Korean");
                case "KS": return _("Kashmiri");
                case "KU": return _("Kurdish");
                case "KV": return _("Komi");
                case "KW": return _("Cornish");
                case "LA": return _("Latin");
                case "LB": return _("Luxembourgish");
                case "LN": return _("Lingala");
                case "LT": return _("Lithuanian");
                case "LV": return _("Latvian");
                case "MG": return _("Malagasy");
                case "MI": return _("Māori");
                case "MK": return _("Macedonian");
                case "ML": return _("Malayalam");
                case "MN": return _("Mongolian");
                case "MR": return _("Marathi");
                case "MS": return _("Malay");
                case "MT": return _("Maltese");
                case "MY": return _("Burmese");
                case "NDS": return _("German (Low)");
                case "NE": return _("Nepali");
                case "NL": return _("Dutch");
                case "NO": return _("Norwegian");
                case "NV": return _("Navajo");
                case "OC": return _("Occitan");
                case "OM": return _("Oromo");
                case "PA": return _("Punjabi");
                case "PI": return _("Pali");
                case "PL": return _("Polish");
                case "PT": return _("Portuguese");
                case "QU": return _("Quechua");
                case "RM": return _("Romansh");
                case "RO": return _("Romanian");
                case "RU": return _("Russian");
                case "SA": return _("Sanskrit");
                case "SC": return _("Sardinian");
                case "SD": return _("Sindhi");
                case "SI": return _("Sinhala");
                case "SK": return _("Slovak");
                case "SL": return _("Slovenian");
                case "SM": return _("Samoan");
                case "SN": return _("Shona");
                case "SO": return _("Somali");
                case "SQ": return _("Albanian");
                case "SR": return _("Serbian");
                case "SV": return _("Swedish");
                case "SW": return _("Swahili");
                case "SWG": return _("German (Swabian)");
                case "TA": return _("Tamil");
                case "TE": return _("Telugu");
                case "TH": return _("Thai");
                case "TK": return _("Turkmen");
                case "TO": return _("Tongan");
                case "TR": return _("Turkish");
                case "TT": return _("Tatar");
                case "TW": return _("Twi");
                case "TY": return _("Tahitian");
                case "UK": return _("Ukrainian");
                case "UR": return _("Urdu");
                case "UZ": return _("Uzbek");
                case "VI": return _("Vietnamese");
                case "WEN": return _("German (Sorbian)");
                case "XH": return _("Xhosa");
                case "YI": return _("Yiddish");
                case "YO": return _("Yoruba");
                case "YUE": return _("Chinese (Cantonese)");
                case "ZH": return _("Chinese");
                case "ZU": return _("Zulu");
                default: return code;
            }
        }
    }
}
