name: receiver
base: core24
version: '0.3.7'
title: Receiver
summary: Discover 30,000+ verified radio stations from around the world
description: |
  Most radio apps make you search for stations by name or paste in a stream
  URL. Receiver ships with over 30,000 stations ready to explore — each one
  individually scanned and verified, with duplicates removed and logos
  fetched in proper resolution. Just open the app and start discovering.

  No sign-up. No ads. No popularity rankings deciding what you hear.
  Just radio.
license: GPL-3.0-or-later
contact: https://github.com/meehow/receiver/issues
issues: https://github.com/meehow/receiver/issues
source-code: https://github.com/meehow/receiver
website: https://github.com/meehow/receiver

grade: stable
confinement: strict
icon: data/icons/hicolor/512x512/apps/io.github.meehow.Receiver.png

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:

slots:
  receiver-mpris:
    interface: mpris

apps:
  receiver:
    command: usr/bin/receiver
    extensions: [gnome]
    environment:
      GIO_USE_PROXY_RESOLVER: gnome
    plugs:
      - network
      - audio-playback
      - desktop
    slots:
      - receiver-mpris

layout:
  /usr/share/receiver:
    bind: $SNAP/usr/share/receiver

parts:
  receiver:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - valac
      - libgtk-4-dev
      - libadwaita-1-dev
      - libgstreamer1.0-dev
      - libsoup-3.0-dev
      - libjson-glib-dev
      - libjavascriptcoregtk-6.0-dev
      - libsqlite3-dev
      - gettext
    stage-packages:
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - libsoup-3.0-0
      - libjson-glib-1.0-0
      - libjavascriptcoregtk-6.0-1
      - libsqlite3-0
      - webp-pixbuf-loader
    stage:
      - -usr/lib/*/libdirect*
      - -usr/lib/*/libharfbuzz*
      - -usr/lib/*/libpango*
      - -usr/lib/*/librsvg*
